{
 "title": "Airbnb Explorer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Airbnb Madrid Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select latitude, longitude, price from listing\r\nlimit 100"
    }
   ]
  },
  {
   "title": "Price Average By Neighbourhood",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select neighbourhood_group, avg(price) from listing\r\nGROUP BY neighbourhood_group"
    }
   ]
  },
  {
   "title": "Room Types Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select room_type, count(room_type) from listing \r\ngroup by room_type"
    }
   ]
  },
  {
   "title": "Minimum Nights Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "select minimum_nights from listing\r\nwhere minimum_nights < 10"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 16 },
   "targets": [
    { "rawSql": "select * from listing " }
   ]
  }
 ]
}